server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/luismellado/kartingapp_microservices.git
          search-paths: back/config-data
  application:
    name: config-service